services:
  todolist:
    container_name: todolist
    image: todolist
    build: 
      context: .
    env_file: 
      - .env
    command: >
      sh -c "flask db upgrade && gunicorn todolist:app -w 2 -b :8000"
    ports:
      - "8000:8000"
